### ISSUE TITLE
Missing include files and Model bin.

### ISSUE THREAD

**Issue by yutaka329** [MarekKowalski/HoloFace#2]
Hi,  
  Great work, I tested the effect ,but miss some include file and model. Can you supplement some files? 
Thank to your open-source.

**Comment by MarekKowalski** [comment]
Hi,

Which include files are you missing? The model files are located in StreamingAssets.

Marek

**Comment by yutaka329** [comment]
Hi,
 I test the "HoloFace/Libraries/src/cTracker3/main.cpp".  this project don`t include  APR related files, such as "FaceInitialization.h".  
 sorry to bother you.

**Comment by MarekKowalski** [comment]
Hi,

You are correct that APR related files are not there (APR was not used in this project). The main.cpp file is included in this project by accident, it is a part of a different project, here I only used it for testing.
The C++ project should still compile fine without the APR part (and without main.cpp).

Let me know if that is not the case.

Marek

**Comment by yutaka329** [comment]
I got it.  moreover,  I hope to see the effect by  main execution if it`s convenient for you.
great work.
Thank you.

**Comment by DmitryBorin** [comment]
Hello!

Could you tell me what face and landmarks detector you use? I read your answer on youtube about using a very fast detector (1000fps on CPU). Where could I find it and what article or methods is it based on?

I also read your article about HoloFace, where you wrote about solutions for mobile devices like MSQRD and other. Can you give a couple of tips on choosing methods to achieve the same accuracy and speed on iPhone? Most interested in the problem with large angles of rotation of the head (60-90 degrees).

Thank you very much for your answers!

**Comment by MarekKowalski** [comment]
Hi,

The facial landmark detector is described in the HoloFace paper that you mentioned. It is a simplified version of a method described in  Face Alignment Using K-Cluster Regression Forests With Weighted Splitting.

As for achieving performance similar to MSQRD and others on mobile devices: achieving a high level of stability as well as robustness is difficult. You can try to use one of my other methods Deep Alignment Network, which is very robust, but I am quite sure it will be too complex to run on a mobile device.

Best regards,

Marek

**Comment by DmitryBorin** [comment]
Hi,

Thank's for your answer! Can you share some trained model for your Face Alignment method (landmarks and face detection)?

Thank you!

**Comment by MarekKowalski** [comment]
Hi,

You can find the code and trained models in one of my other github repositories.

This conversation is off topic. If you have more questions write me an email or start a new issue.

Marek
